# ElasticSearch Configuration for Park Golf Platform

cluster.name: parkgolf-cluster
node.name: ${NODE_NAME}

# Network
network.host: 0.0.0.0
http.port: 9200

# Discovery
discovery.seed_hosts: ["es-node1", "es-node2", "es-node3"]
cluster.initial_master_nodes: ["es-node1"]

# Memory
bootstrap.memory_lock: true

# Data Paths
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

# Korean Language Support
# Nori analyzer for Korean text
indices.analysis.analyzer.default.type: nori

# Security (Production)
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.client_authentication: required
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

# Index Settings
index.number_of_shards: 3
index.number_of_replicas: 1

# Thread Pools
thread_pool.search.size: 20
thread_pool.search.queue_size: 1000
thread_pool.write.size: 10
thread_pool.write.queue_size: 500

# Circuit Breakers
indices.breaker.total.use_real_memory: false
indices.breaker.total.limit: 70%

# Slow Log
index.search.slowlog.threshold.query.warn: 10s
index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.fetch.warn: 1s
index.search.slowlog.threshold.fetch.info: 800ms

# CORS (for development)
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With,Content-Type,Content-Length,Authorization"