openapi: 3.0.0
info:
  title: Park Golf Platform Common API Schemas
  version: 1.0.0
  description: Common schemas used across all services

components:
  schemas:
    # Common Response Schemas
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
        message:
          type: string
      required:
        - success

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object
      required:
        - success
        - error

    PaginationMeta:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
        totalPages:
          type: integer
      required:
        - total
        - page
        - limit
        - totalPages

    PaginatedResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            type: object
        meta:
          $ref: '#/components/schemas/PaginationMeta'

    # Common Entity Schemas
    BaseEntity:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Address:
      type: object
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        country:
          type: string
        latitude:
          type: number
        longitude:
          type: number

    Contact:
      type: object
      properties:
        phone:
          type: string
        email:
          type: string
          format: email
        website:
          type: string
          format: uri

    Money:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
          enum: [KRW, USD, JPY]
      required:
        - amount
        - currency

    TimeSlot:
      type: object
      properties:
        startTime:
          type: string
          format: time
        endTime:
          type: string
          format: time
        duration:
          type: integer
          description: Duration in minutes

  parameters:
    PageParam:
      name: page
      in: query
      schema:
        type: integer
        default: 1
        minimum: 1

    LimitParam:
      name: limit
      in: query
      schema:
        type: integer
        default: 20
        minimum: 1
        maximum: 100

    SortParam:
      name: sort
      in: query
      schema:
        type: string
        pattern: '^[a-zA-Z]+:(asc|desc)$'

    SearchParam:
      name: search
      in: query
      schema:
        type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT