/**
 * 권한 상수 정의
 * 플랫폼의 모든 권한을 중앙에서 관리합니다.
 */

// 플랫폼 레벨 권한
export const PLATFORM_PERMISSIONS = {
  ALL: 'PLATFORM_ALL',
  COMPANY_MANAGE: 'PLATFORM_COMPANY_MANAGE',
  USER_MANAGE: 'PLATFORM_USER_MANAGE',
  SYSTEM_CONFIG: 'PLATFORM_SYSTEM_CONFIG',
  ANALYTICS: 'PLATFORM_ANALYTICS',
  SUPPORT: 'PLATFORM_SUPPORT',
} as const;

// 회사 레벨 권한
export const COMPANY_PERMISSIONS = {
  ALL: 'COMPANY_ALL',
  ADMIN_MANAGE: 'COMPANY_ADMIN_MANAGE',
  COURSE_MANAGE: 'COMPANY_COURSE_MANAGE',
  BOOKING_MANAGE: 'COMPANY_BOOKING_MANAGE',
  USER_MANAGE: 'COMPANY_USER_MANAGE',
  ANALYTICS: 'COMPANY_ANALYTICS',
} as const;

// 코스 레벨 권한
export const COURSE_PERMISSIONS = {
  TIMESLOT_MANAGE: 'COURSE_TIMESLOT_MANAGE',
  BOOKING_MANAGE: 'COURSE_BOOKING_MANAGE',
  CUSTOMER_VIEW: 'COURSE_CUSTOMER_VIEW',
  ANALYTICS_VIEW: 'COURSE_ANALYTICS_VIEW',
} as const;

// 일반 관리 권한
export const GENERAL_PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_COMPANIES: 'MANAGE_COMPANIES',
  MANAGE_COURSES: 'MANAGE_COURSES',
  MANAGE_TIMESLOTS: 'MANAGE_TIMESLOTS',
  MANAGE_BOOKINGS: 'MANAGE_BOOKINGS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ADMINS: 'MANAGE_ADMINS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
} as const;

// 고객 지원 관련 권한
export const SUPPORT_PERMISSIONS = {
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  BOOKING_RECEPTION: 'BOOKING_RECEPTION',
  READ_ONLY: 'READ_ONLY',
} as const;

// 사용자 권한 (일반 사용자용)
export const USER_PERMISSIONS = {
  PROFILE_VIEW: 'PROFILE_VIEW',
  PROFILE_EDIT: 'PROFILE_EDIT',
  COURSE_SEARCH: 'COURSE_SEARCH',
  COURSE_VIEW: 'COURSE_VIEW',
  TIMESLOT_VIEW: 'TIMESLOT_VIEW',
  BOOKING_CREATE: 'BOOKING_CREATE',
  BOOKING_VIEW: 'BOOKING_VIEW',
  BOOKING_MODIFY: 'BOOKING_MODIFY',
  BOOKING_CANCEL: 'BOOKING_CANCEL',
  BOOKING_HISTORY: 'BOOKING_HISTORY',
  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_HISTORY: 'PAYMENT_HISTORY',
  REFUND_REQUEST: 'REFUND_REQUEST',
  PREMIUM_BOOKING: 'PREMIUM_BOOKING',
  PRIORITY_BOOKING: 'PRIORITY_BOOKING',
  ADVANCED_SEARCH: 'ADVANCED_SEARCH',
} as const;

// 모든 권한을 하나의 객체로 통합
export const ALL_PERMISSIONS = {
  ...PLATFORM_PERMISSIONS,
  ...COMPANY_PERMISSIONS,
  ...COURSE_PERMISSIONS,
  ...GENERAL_PERMISSIONS,
  ...SUPPORT_PERMISSIONS,
  ...USER_PERMISSIONS,
} as const;

// 권한 배열로 변환
export const ALL_PERMISSIONS_ARRAY = Object.values(ALL_PERMISSIONS);

// 관리자 권한만 추출 (사용자 권한 제외)
export const ADMIN_PERMISSIONS_ARRAY = [
  ...Object.values(PLATFORM_PERMISSIONS),
  ...Object.values(COMPANY_PERMISSIONS),
  ...Object.values(COURSE_PERMISSIONS),
  ...Object.values(GENERAL_PERMISSIONS),
  ...Object.values(SUPPORT_PERMISSIONS),
];

// 권한 타입 정의
export type Permission = string;
export type AdminPermission = string;
export type UserPermission = string;

// 권한 그룹별 설명
export const PERMISSION_DESCRIPTIONS = {
  [PLATFORM_PERMISSIONS.ALL]: '플랫폼 전체 관리 권한',
  [PLATFORM_PERMISSIONS.COMPANY_MANAGE]: '플랫폼 내 회사 관리',
  [PLATFORM_PERMISSIONS.USER_MANAGE]: '플랫폼 사용자 관리',
  [PLATFORM_PERMISSIONS.SYSTEM_CONFIG]: '시스템 설정 관리',
  [PLATFORM_PERMISSIONS.ANALYTICS]: '플랫폼 분석 데이터 조회',
  [PLATFORM_PERMISSIONS.SUPPORT]: '플랫폼 고객 지원',
  
  [COMPANY_PERMISSIONS.ALL]: '회사 전체 관리 권한',
  [COMPANY_PERMISSIONS.ADMIN_MANAGE]: '회사 관리자 관리',
  [COMPANY_PERMISSIONS.COURSE_MANAGE]: '회사 코스 관리',
  [COMPANY_PERMISSIONS.BOOKING_MANAGE]: '회사 예약 관리',
  [COMPANY_PERMISSIONS.USER_MANAGE]: '회사 사용자 관리',
  [COMPANY_PERMISSIONS.ANALYTICS]: '회사 분석 데이터 조회',
  
  [COURSE_PERMISSIONS.TIMESLOT_MANAGE]: '타임슬롯 관리',
  [COURSE_PERMISSIONS.BOOKING_MANAGE]: '예약 관리',
  [COURSE_PERMISSIONS.CUSTOMER_VIEW]: '고객 정보 조회',
  [COURSE_PERMISSIONS.ANALYTICS_VIEW]: '코스 분석 데이터 조회',
  
  [GENERAL_PERMISSIONS.VIEW_DASHBOARD]: '대시보드 조회',
  [GENERAL_PERMISSIONS.MANAGE_COMPANIES]: '회사 관리',
  [GENERAL_PERMISSIONS.MANAGE_COURSES]: '코스 관리',
  [GENERAL_PERMISSIONS.MANAGE_TIMESLOTS]: '타임슬롯 관리',
  [GENERAL_PERMISSIONS.MANAGE_BOOKINGS]: '예약 관리',
  [GENERAL_PERMISSIONS.MANAGE_USERS]: '사용자 관리',
  [GENERAL_PERMISSIONS.MANAGE_ADMINS]: '관리자 관리',
  [GENERAL_PERMISSIONS.VIEW_ANALYTICS]: '분석 데이터 조회',
  
  [SUPPORT_PERMISSIONS.CUSTOMER_SUPPORT]: '고객 지원',
  [SUPPORT_PERMISSIONS.BOOKING_RECEPTION]: '예약 접수',
  [SUPPORT_PERMISSIONS.READ_ONLY]: '읽기 전용',
} as const;