steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ml-service:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/ml-service:latest', '.']
    dir: 'services/ml-service'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/ml-service']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ml-service-$_ENVIRONMENT'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ml-service:$SHORT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--min-instances'
      - '$_MIN_INSTANCES'
      - '--max-instances'
      - '$_MAX_INSTANCES'
      - '--port'
      - '3016'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PYTHON_ENV=$_ENVIRONMENT,GCP_PROJECT=$PROJECT_ID,NATS_URL=$_NATS_URL,DATABASE_URL=$_DATABASE_URL,REDIS_URL=$_REDIS_URL'
      - '--memory'
      - '$_MEMORY'
      - '--cpu'
      - '$_CPU'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '10'

substitutions:
  _ENVIRONMENT: 'development'
  _REGION: 'asia-northeast3'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '5'
  _MEMORY: '1Gi'
  _CPU: '2'
  _NATS_URL: 'nats://nats:4222'
  _DATABASE_URL: 'postgresql://ml_service@/ml_service?host=/cloudsql/CONNECTION_NAME'
  _REDIS_URL: 'redis://redis:6379'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'