version: '3.8'

services:
  ml-services:
    build:
      context: ./ml-services
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - ML_SERVICE_PORT=4000
    volumes:
      - ./ml-services/models:/app/models
      - ./ml-services/data:/app/data
    depends_on:
      - mongodb
      - redis
    networks:
      - parkgolf-ml-network

  mcp-services:
    build:
      context: ./mcp-services
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - MCP_SERVICE_PORT=4001
    depends_on:
      - mongodb
      - redis
    networks:
      - parkgolf-ml-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - parkgolf-ml-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - parkgolf-ml-network

networks:
  parkgolf-ml-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: