steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/search-service:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/search-service:latest', '.']
    dir: 'services/search-service'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/search-service']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'search-service-$_ENVIRONMENT'
      - '--image'
      - 'gcr.io/$PROJECT_ID/search-service:$SHORT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--min-instances'
      - '$_MIN_INSTANCES'
      - '--max-instances'
      - '$_MAX_INSTANCES'
      - '--port'
      - '3015'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GO_ENV=$_ENVIRONMENT,GCP_PROJECT=$PROJECT_ID,NATS_URL=$_NATS_URL,ELASTICSEARCH_URL=$_ELASTICSEARCH_URL,REDIS_URL=$_REDIS_URL'
      - '--memory'
      - '$_MEMORY'
      - '--cpu'
      - '$_CPU'
      - '--timeout'
      - '300'

substitutions:
  _ENVIRONMENT: 'development'
  _REGION: 'asia-northeast3'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _MEMORY: '512Mi'
  _CPU: '1'
  _NATS_URL: 'nats://nats:4222'
  _ELASTICSEARCH_URL: 'http://elasticsearch:9200'
  _REDIS_URL: 'redis://redis:6379'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'