# platform dev override
global:
  namespace: parkgolf-dev
  domain: dev-api.parkgolfmate.com
  image:
    tag: e335d18d6c03b4a3bb6d236e47d16b4597fda5a4
externalSecrets:
  clusterName: parkgolf-dev-cluster
  clusterLocation: asia-northeast3-a
ingress:
  staticIpName: parkgolf-parkgolf-dev-cluster-ip
serviceImageTags:
  iam-service: e335d18d6c03b4a3bb6d236e47d16b4597fda5a4
  notify-service: e335d18d6c03b4a3bb6d236e47d16b4597fda5a4
  weather-service: e335d18d6c03b4a3bb6d236e47d16b4597fda5a4
  location-service: e335d18d6c03b4a3bb6d236e47d16b4597fda5a4
  job-service: e335d18d6c03b4a3bb6d236e47d16b4597fda5a4
