steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/auth-service:latest', '.']
    dir: 'services/auth-service'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/auth-service']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auth-service-$_ENVIRONMENT'
      - '--image'
      - 'gcr.io/$PROJECT_ID/auth-service:$SHORT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--min-instances'
      - '$_MIN_INSTANCES'
      - '--max-instances'
      - '$_MAX_INSTANCES'
      - '--port'
      - '3011'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=$_ENVIRONMENT,GCP_PROJECT=$PROJECT_ID,NATS_URL=$_NATS_URL,DATABASE_URL=$_DATABASE_URL,REDIS_URL=$_REDIS_URL,JWT_SECRET=$_JWT_SECRET'
      - '--add-cloudsql-instances'
      - '$_CLOUDSQL_INSTANCE'
      - '--memory'
      - '$_MEMORY'
      - '--cpu'
      - '$_CPU'
      - '--timeout'
      - '300'

substitutions:
  _ENVIRONMENT: 'development'
  _REGION: 'asia-northeast3'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _MEMORY: '512Mi'
  _CPU: '1'
  _NATS_URL: 'nats://nats:4222'
  _DATABASE_URL: 'postgresql://auth_service@/auth_service?host=/cloudsql/CONNECTION_NAME'
  _REDIS_URL: 'redis://redis:6379'
  _JWT_SECRET: 'SECRET_FROM_SECRET_MANAGER'
  _CLOUDSQL_INSTANCE: 'PROJECT:REGION:INSTANCE'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'